### ISSUE TITLE
Unable to reconnect

### ISSUE THREAD

**Issue by mlaitinen** [loklaan/luxafor-for-slack#1]
When I detach Luxafor from my laptop and later plug it back in, `luxafor-for-slack` is unable to reconnect to the device. At first the light stays off and after changing my status in Slack, I only get the stack trace below.

```
 DnD   Disabled. Set to enable at 10:00:00 PM.
Error: Cannot write to HID device
    at Luxafor.write (/usr/lib/node_modules/luxafor-for-slack/node_modules/luxafor-api/src/luxafor.js:34:19)
    at Luxafor.setColor (/usr/lib/node_modules/luxafor-for-slack/node_modules/luxafor-api/src/luxafor.js:52:10)
    at processLuxaforColor (/usr/lib/node_modules/luxafor-for-slack/src/util.js:132:11)
    at setDnd (/usr/lib/node_modules/luxafor-for-slack/src/util.js:93:3)
    at configureDndTimer (/usr/lib/node_modules/luxafor-for-slack/src/util.js:75:5)
    at Object.handleDnd (/usr/lib/node_modules/luxafor-for-slack/src/util.js:127:7)
    at Object.bot.dnd_updated.message (/usr/lib/node_modules/luxafor-for-slack/index.js:100:15)
    at /usr/lib/node_modules/luxafor-for-slack/node_modules/slack/methods/rtm.client.js:54:20
    at Array.forEach (native)
    at WebSocket.message (/usr/lib/node_modules/luxafor-for-slack/node_modules/slack/methods/rtm.client.js:53:18)
 DnD   Disabled. Set to enable at 11:06:44 AM.
Error: Cannot write to HID device
    at Luxafor.write (/usr/lib/node_modules/luxafor-for-slack/node_modules/luxafor-api/src/luxafor.js:34:19)
    at Luxafor.setColor (/usr/lib/node_modules/luxafor-for-slack/node_modules/luxafor-api/src/luxafor.js:52:10)
    at processLuxaforColor (/usr/lib/node_modules/luxafor-for-slack/src/util.js:132:11)
    at setDnd (/usr/lib/node_modules/luxafor-for-slack/src/util.js:93:3)
    at configureDndTimer (/usr/lib/node_modules/luxafor-for-slack/src/util.js:48:7)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
 DnD   Enabled. Set to disable at 11:07:44 AM.
```

A good solution would probably be to monitor USB devices and initialize the device after re-attaching it. Or frequently polling the device.

I'm not sure if this issue belongs here or to the [luxafor-api](https://github.com/iamthefox/luxafor) project.

**Comment by loklaan** [comment]
Hey - it might be because I haven't updated to the latest luxafor-api... Otherwise, it's a problem in that package.

If you want to dive into it further, that would be appreciated! @iamthefox has done a superb job at making his package approachable, so if the fix is on that end, you'll have a good time while coding. 👌 

Let me know if you want to proceed with this yourself. Otherwise, I'll put it in my backlog and get around to it one day.

**Comment by mlaitinen** [comment]
I tried this with the most recent `luxafor-api`, but that didn't fix the issue. I think there are two problems here:

1. After reattaching Luxafor, any commands sent to it cause the "Cannot write to HID device" error. This is probably because `luxafor-api` has a stale handle to the device. I suppose this should be fixed in the `luxafor-api` project.
1. Even if the aforementioned problem was fixed, `luxafor-for-slack` would have to somehow detect the reattach action and send the current status color to Luxafor. Otherwise the color would only change when the DnD status changed. This should be fixed in the `luxafor-for-slack` project.

I have never done anything in Node.js but I could try. I do have some basic JS experience. Do you have any idea how we could "ping" the device or detect HID unplug and plug events, @loklaan?

**Comment by loklaan** [comment]
Hey Miku - thanks for making the effort!

This is a pretty good feature to get your hands wet with node.js. I think you'll be able to accomplish the fix 👍 

Some things to consider:

**`luxafor-api`**

- Under the hood this uses another package, [`node-hid`](https://github.com/node-hid/node-hid).
   It can [subscribe](https://github.com/node-hid/node-hid#reading-from-a-device) to data events from devices - you might be able to pick up a 'close' data packet to detect disconnects / connects. Otherwise, setup polling maybe..
- This could be exposed on the `luxafor-api` export as an `on()` function that emits `'connect'` and `'disconnect'` events?

**`luxafor-for-slack`**

- Use the new `on()` api you exposed to trigger behaviours based on events.

---

Since you're new to node.js dev, it might be worth mentioning that developing multiple packages locally is made a lot easier by using `npm link`.

Goodluck! Let me know how it goes. I can give some more advice too if you have pointed questions.

**Comment by loklaan** [comment]
Closing due to inactivity.

If anyone makes it to this thread and would like to pick it up, let me know!
